'''Regression tests proving that free-text tool parameters (server/app names,
targets, paths) cannot break out of their string literal in the WLST/Jython
scripts generated by each tool.

Strategy: generate the script for a "safe" baseline value and for a malicious
value with the same shape of input, then assert the *set* of function/method
calls and import statements is identical between the two. If a payload breaks
out of its string literal (e.g. via `'); import os; os.system(...); ('`), the
malicious script will contain extra calls (`system`) and/or extra `import`
statements that the safe baseline does not -- which is exactly what injected
code looks like from the outside.
'''
import asyncio
import ast

import pytest

import wlst_mcp


INJECTION_PAYLOADS = [
    "O'Brien",
    "'); import os; os.system('echo pwned'); ('",
    "trailing-quote'",
]


def _capture_script(monkeypatch, tool_fn, params):
    captured = {}

    async def fake_execute(script, timeout=None):
        captured["script"] = script
        return {"success": False, "returncode": 1, "stdout": "", "stderr": "", "error": "mocked"}

    monkeypatch.setattr(wlst_mcp, "_execute_wlst_script", fake_execute)
    asyncio.run(tool_fn(params))
    return captured["script"]


def _call_names(script):
    tree = ast.parse(script, mode="exec")
    names = []
    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            if isinstance(node.func, ast.Name):
                names.append(node.func.id)
            elif isinstance(node.func, ast.Attribute):
                names.append(node.func.attr)
    return sorted(names)


def _import_count(script):
    tree = ast.parse(script, mode="exec")
    return sum(1 for n in ast.walk(tree) if isinstance(n, (ast.Import, ast.ImportFrom)))


class ToolCase:
    def __init__(self, tool_fn, model_cls, field_name, base_kwargs=None):
        self.tool_fn = tool_fn
        self.model_cls = model_cls
        self.field_name = field_name
        self.base_kwargs = base_kwargs or {}

    @property
    def id(self):
        return f"{self.tool_fn.__name__}:{self.field_name}"


TOOL_CASES = [
    ToolCase(wlst_mcp.wlst_start_server, wlst_mcp.ServerOperationInput, "server_name"),
    ToolCase(wlst_mcp.wlst_stop_server, wlst_mcp.ServerOperationInput, "server_name"),
    ToolCase(wlst_mcp.wlst_restart_server, wlst_mcp.ServerOperationInput, "server_name"),
    ToolCase(wlst_mcp.wlst_server_metrics, wlst_mcp.ServerMetricsInput, "server_name"),
    ToolCase(wlst_mcp.wlst_thread_dump, wlst_mcp.ThreadDumpInput, "server_name"),
    ToolCase(wlst_mcp.wlst_server_health, wlst_mcp.ServerHealthInput, "server_name"),
    ToolCase(wlst_mcp.wlst_analyze_logs, wlst_mcp.ServerLogsInput, "server_name"),
    ToolCase(wlst_mcp.wlst_start_application, wlst_mcp.AppOperationInput, "app_name"),
    ToolCase(wlst_mcp.wlst_stop_application, wlst_mcp.AppOperationInput, "app_name"),
    ToolCase(wlst_mcp.wlst_redeploy_application, wlst_mcp.AppOperationInput, "app_name"),
    ToolCase(wlst_mcp.wlst_undeploy, wlst_mcp.UndeployInput, "app_name"),
    ToolCase(wlst_mcp.wlst_diagnose_application, wlst_mcp.AppDiagnosticInput, "app_name"),
    ToolCase(wlst_mcp.wlst_deploy, wlst_mcp.DeployInput, "app_name", {"app_path": "/apps/safe.war"}),
    ToolCase(wlst_mcp.wlst_deploy, wlst_mcp.DeployInput, "app_path", {"app_name": "safe-app"}),
    ToolCase(wlst_mcp.wlst_deploy, wlst_mcp.DeployInput, "targets", {"app_name": "safe-app", "app_path": "/apps/safe.war"}),
    ToolCase(wlst_mcp.wlst_undeploy, wlst_mcp.UndeployInput, "targets", {"app_name": "safe-app"}),
]


@pytest.mark.parametrize("case", TOOL_CASES, ids=[c.id for c in TOOL_CASES])
@pytest.mark.parametrize("malicious_value", INJECTION_PAYLOADS)
def test_tool_script_generation_resists_injection(case, malicious_value, monkeypatch):
    safe_kwargs = {**case.base_kwargs, case.field_name: "safe-value"}
    malicious_kwargs = {**case.base_kwargs, case.field_name: malicious_value}

    safe_script = _capture_script(monkeypatch, case.tool_fn, case.model_cls(**safe_kwargs))
    malicious_script = _capture_script(monkeypatch, case.tool_fn, case.model_cls(**malicious_kwargs))

    # Must still be syntactically valid WLST/Jython source.
    ast.parse(malicious_script, mode="exec")

    assert _call_names(malicious_script) == _call_names(safe_script), (
        "malicious payload introduced unexpected function calls -- likely broke out of its string literal"
    )
    assert _import_count(malicious_script) == _import_count(safe_script), (
        "malicious payload introduced an import statement -- broke out of its string literal"
    )
